---
title: "tochi_perceived_burden"
output: html_document
date: "2023-12-23"
---

## import libraries
```{r}

library(ggplot2)
library(psych)
library(reshape2)
library(dplyr)
library(lsr)
library(car)

```

## Read in the burden file
```{r}

perceived_burden_data <- read.csv(file = "/Users/adityaponnada/Downloads/time_study_data/perceived_burden.csv", sep = ",", header = TRUE)

```

## Split into 6m and exit survey dfs

First, get the column names and then split column names into two
```{r}

all_col_names <- names(perceived_burden_data)

```

Get column names for 6 months survey
```{r}

common_cols <- c(1:3)

phone_6m_cols <- c(c(4: 20), c(23, 24))
watch_6m_cols <- c(c(28: 44), c(47, 48))

phone_12m_cols <- c(c(53: 69), c(72, 73))
watch_12m_cols <- c(c(83: 99), c(102, 103))



```

#### Note that the status 3, 4, and 5 are: withdrawn, unenrolled, and completed statuses. This can be mapped to 0, 1, 2 for convinience

```{r}

id_df <- perceived_burden_data[, common_cols]
colnames(id_df) <- c("index", "participant_ID", "participant_status_code")

```

```{r}

id_df$status_type[id_df$participant_status_code == 3] = 'Withdrawn'
id_df$status_type[id_df$participant_status_code == 4] = 'Unenrolled'
id_df$status_type[id_df$participant_status_code == 5] = 'Completed'


```

```{r}
burden_6m_df <- perceived_burden_data[, c(phone_6m_cols, watch_6m_cols)]
burden_12m_df <- perceived_burden_data[, c(phone_12m_cols, watch_12m_cols)]
```

```{r}

burden_6m_df$phone_total_burden <- rowSums(burden_6m_df[, c(1:19)])
burden_6m_df$watch_total_burden <- rowSums(burden_6m_df[, c(20:38)])

```

```{r}

burden_12m_df$phone_total_burden <- rowSums(burden_12m_df[, c(1:19)])
burden_12m_df$watch_total_burden <- rowSums(burden_12m_df[, c(20:38)])

```


```{r}
burden_6m_df <- cbind(id_df, burden_6m_df)
burden_12m_df <- cbind(id_df, burden_12m_df)
```


```{r}

burden_6m_no_na_df <- burden_6m_df[(!is.na(burden_6m_df$phone_total_burden)) & (!is.na(burden_6m_df$watch_total_burden)), ]

```

```{r}

burden_12m_no_na_df <- burden_12m_df[(!is.na(burden_12m_df$phone_total_burden)) & (!is.na(burden_12m_df$watch_total_burden)), ]

```

```{r}

burden_12m_no_na_df <- burden_12m_no_na_df[burden_12m_no_na_df$status_type == "Completed", ]

```

```{r}

describe(burden_6m_no_na_df$phone_total_burden)
describe(burden_6m_no_na_df$watch_total_burden)

```
```{r}

describe(burden_12m_no_na_df$phone_total_burden)
describe(burden_12m_no_na_df$watch_total_burden)

```

```{r}

summary(burden_12m_no_na_df$phone_total_burden)
summary(burden_12m_no_na_df$watch_total_burden)

```


```{r}

describeBy(burden_6m_no_na_df$phone_total_burden,burden_6m_no_na_df$status_type)
describeBy(burden_6m_no_na_df$watch_total_burden,burden_6m_no_na_df$status_type)

```

```{r}

t.test(burden_12m_no_na_df$phone_total_burden, burden_12m_no_na_df$watch_total_burden, paired = TRUE, alternative = "two.sided")


```
```{r}

long_12m_burden_df <- melt(burden_12m_no_na_df, id.vars='participant_ID', measure.vars=c('phone_total_burden', 'watch_total_burden')) 

```

```{r}
plot_df_12m <- long_12m_burden_df
plot_df_12m$METHOD[plot_df_12m$variable == 'phone_total_burden'] <- "EMA"
plot_df_12m$METHOD[plot_df_12m$variable == 'watch_total_burden'] <- gsub(" ", "", paste('\U00B5','EMA'))
```


```{r}

# burden_12m_plot <- ggplot(long_12m_burden_df) + geom_boxplot(aes(x=variable, y=value)) + theme_bw()

```

```{r}
burden_12m_plot <- ggplot(plot_df_12m, aes(METHOD, value,fill=METHOD)) + geom_violin() +
  scale_fill_manual('Method', values = c('coral', 'cadetblue3')) +
  theme_bw() +
  ggtitle("Only completed participants") +
  xlab('') +
  ylab('Perceived burden at 12 months') +
  ylim(19, 95) +
  theme(text = element_text(size=15),
        axis.text.x = element_text(size=15), title = element_text(size=15), legend.position='none') +
  stat_summary(fun.data=mean_sdl, fun.args = list(mult = 1),
               geom="pointrange", color="black",
               shape = 18, size = 0.75,
               position = position_dodge(width = 0.9))
```


```{r}
cohensD(value~variable, data = long_12m_burden_df) 
```


```{r}

long_6m_burden_df <- melt(burden_6m_no_na_df, id.vars='participant_ID', measure.vars=c('phone_total_burden', 'watch_total_burden'))

```

```{r}

long_6m_burden_df <- merge(x = long_6m_burden_df, y = burden_6m_no_na_df[ , c("participant_ID", "status_type")], by = "participant_ID", all.x=TRUE)

```

```{r}

res.aov2 <- aov(value ~ variable + status_type + variable:status_type, data = long_6m_burden_df)
# summary(res.aov2)
Anova(res.aov2, type = "III")

```
```{r}
etaSquared(res.aov2)

```
```{r}
tukey_type <- TukeyHSD(res.aov2, conf.level = 0.95, which = "variable")
```

```{r}
tukey_type
```
```{r}
plot(tukey_type)
```


```{r}

tukey_result <- TukeyHSD(res.aov2, conf.level = 0.95, which = "status_type")

```

```{r}
tukey_result
```


```{r}
plot(tukey_result)
```




```{r}

bp <- ggplot(long_6m_burden_df, aes(x=variable, y=value, group=variable)) + 
  geom_boxplot() + labs(y="Perceived Burden")
# bp

bp <- bp + facet_grid(. ~ status_type) + theme_bw()  + theme(text= element_text(size=15), axis.text.x= element_text(size=15), axis.title.x = element_blank())

```

```{r}
# p <- ggplot(plot_df_long, aes(variable, value,fill=TYPE)) + geom_boxplot() + facet_wrap(~STATUS) + theme_bw() +
#   theme(text = element_text(size=20),
#         axis.text.x = element_text(size=15))
```

```{r}
ggplot(long_6m_burden_df, 
       aes(x = status_type, y = value, colour = variable, group = variable)) +
  geom_line()
```

```{r}

interaction.plot(x.factor = long_6m_burden_df$status_type, #x-axis variable
                 trace.factor = long_6m_burden_df$variable, #variable for lines
                 response = long_6m_burden_df$value, #y-axis variable
                 fun = mean, #metric to plot
                 ylab = "Perceived Burden after 6 months",
                 xlab = "Participant Status",
                 col = c("coral", "cadetblue3"),
                 type = "b",
                 pch=c(16, 17),
                 lty = c(1, 1), #line type
                 lwd = 3, #line width
                 xtick=TRUE,
                 legend=FALSE,
                 ylim=c(19, 95))
par(xpd=TRUE)
legend("topleft", legend=c("EMA", gsub(" ", "", paste('\U00B5','EMA'))), 
       lty = c(1,2), 
       lwd=2, 
       col=c("coral", "cadetblue3"), 
       pch = c(16, 17), 
       title="Method")

```


```{r}
long_6m_burden_df %>% 
  group_by(status_type, variable) %>% 
  summarise(burden_groups = mean(value)) -> df_test

names(df_test) <- c("Status", "Type", "Burden")
df_test$Method[df_test$Type == 'phone_total_burden'] <- 'EMA'
df_test$Method[df_test$Type == 'watch_total_burden'] <- gsub(" ", "", paste('\U00B5','EMA'))


 interaction_plot_6m <-  ggplot(df_test) +
  aes(x = Status, y = Burden, color = Method) +
  geom_line(aes(group = Method)) +
    scale_fill_manual('Method', values = c('coral', 'cadetblue3')) +
  geom_point() +
    theme_bw() +
  xlab('') +
  ylab('Perceived burden at 6 months') +
  ylim(19, 95) +
  theme(text = element_text(size=15),
        axis.text.x = element_text(size=15), title = element_text(size=15), legend.position='top', legend.justification.top = "right")
  
  
  # burden_12m_plot <- ggplot(plot_df_12m, aes(METHOD, value,fill=METHOD)) + geom_violin() +
  # scale_fill_manual('Method', values = c('coral', 'cadetblue3')) +
  # theme_bw() +
  # ggtitle("Only completed participants") +
  # xlab('') +
  # ylab('Perceived burden at 12 months') +
  # ylim(19, 95) +
  # theme(text = element_text(size=15),
  #       axis.text.x = element_text(size=15), title = element_text(size=15), legend.position='none') +
  # stat_summary(fun.data=mean_sdl, fun.args = list(mult = 1),
  #              geom="pointrange", color="black",
  #              shape = 18, size = 0.75,
  #              position = position_dodge(width = 0.9))
```




```{r}
ggplot(long_6m_burden_df) +
  aes(x = status_type, y = value, color = variable) +
  geom_line(aes(group = variable))
```



```{r}

completed_burden_12m <- burden_12m_no_na_df[c("participant_ID", "phone_total_burden", "watch_total_burden")]
completed_burden_6m <- burden_6m_no_na_df[c("participant_ID", "phone_total_burden", "watch_total_burden")]

names(completed_burden_12m) <- c("participant_ID", "phone_total_burden_12m", "watch_total_burden_12m")
names(completed_burden_6m) <- c("participant_ID", "phone_total_burden_6m", "watch_total_burden_6m")


```

```{r}

burden_diff_df <- merge(completed_burden_12m, completed_burden_6m, by="participant_ID")

```

```{r}

burden_diff_df$phone_burden_diff <- burden_diff_df$phone_total_burden_12m - burden_diff_df$phone_total_burden_6m
burden_diff_df$watch_burden_diff <- burden_diff_df$watch_total_burden_12m - burden_diff_df$watch_total_burden_6m

```

```{r}

hist(burden_diff_df$phone_burden_diff)

```

```{r}

hist(burden_diff_df$watch_burden_diff)

```
```{r}

test_diff_df <- melt(burden_diff_df[c("participant_ID", "phone_burden_diff", "watch_burden_diff")], id.vars=c("participant_ID"))

```

```{r}

ggplot(test_diff_df, aes(x = value, fill = variable)) +
  geom_histogram(position = "identity", alpha = 0.4, bins = 50) +
  labs(x="Change in perceived burden", y="Number of users") +
  theme_bw()
  

```

```{r}

ggplot(test_diff_df, aes(x = variable, y = value)) + 
  geom_boxplot() +
  labs(x="", y="Change in perceived burden") +
  theme_bw()

```
```{r}

t.test(burden_diff_df$phone_burden_diff, burden_diff_df$watch_burden_diff, paired = TRUE, alternative = "two.sided")

```

